src folder for code review
utsav-deep-rjil/jcs-sdk pull request #2
Opened 2016-10-25 06:37 UTC by utsav-deep-rjil

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/auth/Authorization.java
> +        }
Better to throw an exception if host and port ar not valid. Do you want to consider this ?

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/auth/Authorization.java
> +    public String sortParams(Map<String, String> params) throws UnsupportedEncodingException {
its probably Serializing the params so sort is not the right name here

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/auth/BasicJCSCredentials.java
> +        if (accessKey == null) {
Do Something like StringUtils.isNotBlank
AS "" "   " are all invalid strings

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/auth/BasicJCSCredentials.java
> +            throw new IllegalArgumentException("Secret key cannot be null.");
Ditto!

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/auth/ConfigPropertiesCredentialsProvider.java
> +            throw new RuntimeException("Unable to load JCS credentials from config.properties file (" + accessKey
Use String.format

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/auth/EnvironmentVariableCredentialsProvider.java
> +        if (Utils.isNullOrEmpty(accessKey) || Utils.isNullOrEmpty(secretKey)) {
Use StringUtils

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/auth/JCSCredentials.java
> +public interface JCSCredentials {
Java docs on methods

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/auth/JCSCredentialsProviderChain.java
> +                    log.debug("Loading credentials from " + provider.toString());
Remove the debug line here

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/auth/JCSCredentialsProviderChain.java
> +                log.debug("Unable to load credentials from " + provider.toString() + ": " + e.getMessage());
This is an exception. it should either be a warn or error

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/auth/JCSCredentialsProviderChain.java
> +        throw new RuntimeException("Unable to load JCS credentials from any provider in the chain");
Throw the exception as RuntimeException(e)

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/common/JCSHttpClient.java
> +            ;
Remove this

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/common/JCSHttpClient.java
> +        System.out.println("Response Code: " + closeableHttpResponse.getStatusLine().getStatusCode());
Remove this

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/common/JCSHttpClient.java
> +    private String getUrl(Map<String, String> params) {
Advisable to use string builders here

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/common/PropertiesReader.java
> +            e1.printStackTrace();
use loggers

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/common/Utils.java
> +        Pattern r = Pattern.compile("(http[s]?)://((?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*(),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+)");
Use a string constant for the pattern

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/common/Utils.java
> +            protocolAndHost.setProtocol("");
What happens when protocol and host are empty ?

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/common/Utils.java
> +    public static boolean isNullOrEmpty(String value) {
Remove this. Use StringUtils else where

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/main/JCStry.java
> +package com.jcs.sbs.main;
Remove this test file from SDK

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/model/DescribeSnapshotsResult.java
> +            snapshots = new ArrayList<Snapshot>();
Why not initialize snapshots = new ArrayList<Snapshot>(); at the time of object creation ??
Follow this pattern elsewhere

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/model/DescribeVolumesRequest.java
> +            volumeIds = new ArrayList<String>();
Ditto explained above

2016-11-02 07:34 UTC, sssouvik commented on src/main/java/com/jcs/sbs/service/impl/JCSComputeClient.java
> +                System.out.println(content);
Remove this

2016-11-02 07:34 UTC, sssouvik commented on src/test/java/com/jcs/sbs/service/JCSComputeTest.java
> +public class JCSComputeTest {
Remove this from SDK

2016-11-04 08:16 UTC, utsav-deep-rjil commented on src/main/java/com/jcs/sbs/auth/JCSCredentialsProviderChain.java
> +                    log.debug("Loading credentials from " + provider.toString());
I think user should be informed which credentials is actually being used in SDK. If the user had set the credentials at all the places (config.properties, environment variables and system properties) but all are different, then this info will be helpful.
BTW, I am changing the 'debug' into 'info'

2016-11-10 07:47 UTC, aggarwalchirag requested changes

2016-11-10 07:47 UTC, aggarwalchirag commented on src/main/java/com/jcs/sbs/model/Snapshot.java
> +    public String toString() {
starttime and status are not captured in toString

2016-11-10 07:47 UTC, aggarwalchirag commented on src/main/java/com/jcs/sbs/model/Snapshot.java
> +    @Override
here also, starttime and status are not used

2016-11-10 07:47 UTC, aggarwalchirag commented on src/main/java/com/jcs/sbs/model/Snapshot.java
> +
here as well

2016-11-10 07:47 UTC, aggarwalchirag commented on src/main/java/com/jcs/sbs/model/Volume.java
> +	 */
where is attachment set information ?

2016-11-10 07:47 UTC, aggarwalchirag commented on src/main/java/com/jcs/sbs/model/Volume.java
> +
all members are not used here

2016-11-10 07:47 UTC, aggarwalchirag commented on src/main/java/com/jcs/sbs/model/Volume.java
> +
why is this initialized to true ?

2016-11-10 07:56 UTC, aggarwalchirag requested changes

2016-11-10 07:56 UTC, aggarwalchirag commented on src/main/java/com/jcs/sbs/model/DescribeSnapshotsRequest.java
> +            this.snapshotIds = new ArrayList<String>();
why do you need this. You initialized snapshots in the constructor itself. I can imagine a case, where someone calls up this function twice. In that scenario the change makes sense. But then you should handle it in withSnapshotIds as well.

2016-11-14 06:39 UTC, aggarwalchirag approved these changes
The code looks much cleaner now. @utsav-deep-rjil : Good Job.

2016-11-14 08:09 UTC, merged